import { describe, expect, it } from 'vitest';
import { AgentSchema, IssueSchema, IssueStatusSchema, IssueTypeSchema, DependencyTypeSchema, RunSchema, agentFromBdWire, agentSlug, agentToBdWire, dependencyTarget, issueFromBdWire, issueId, issuePriority, issueTitle, issueToBdWire, runFromBdWire, runId, runToBdWire, transitionStatus } from '../src/index.js';

const timestamps = { encode: (value: Date) => `wire:${value.toISOString()}`, decode: (value: string) => { if (!value.startsWith('wire:')) throw new Error('codec boundary used'); return new Date(value.slice(5)); } };
const createdAt = 'wire:2025-01-01T00:00:00.000Z';
const updatedAt = 'wire:2025-01-02T00:00:00.000Z';
const json = { schema_version: 1 as const, _type: 'issue' as const, id: 'tk-5au', title: 'Plan phase one', description: 'Architecture', status: 'queued-custom', priority: 2, issue_type: 'release-candidate', owner: 'owner@example.test', assignee: 'worker', created_by: 'Yuri', created_at: createdAt, updated_at: updatedAt, started_at: 'wire:2025-01-01T01:00:00.000Z', due_at: 'wire:2025-01-04T00:00:00.000Z', defer_until: null, parent: 'tk-epic', labels: ['architecture'], notes: 'note', design: 'design', acceptance_criteria: 'tests pass', estimate: 3, spec_id: 'spec/phase-1', external_ref: 'GH-42', branch: 'feature/hunk', metadata: '{"agent":"conductor"}', dependencies: [{ issue_id: 'tk-5au', depends_on_id: 'external:other:shipped-api', type: 'awaiting-release', created_at: createdAt, created_by: 'Yuri', metadata: '{}', edge_future: { retained: true } }], dependency_count: 1, comments: [{ id: 'comment-1', issue_id: 'tk-5au', author: 'Yuri', text: 'hello', created_at: createdAt, comment_future: ['kept'] }], comment_count: 1, future_field: { retained: true } };

describe('tk-compatible issue domain', () => {
  it('brands local IDs, allows explicit external targets', () => { expect(issueId('tk-5au')).toBe('tk-5au'); expect(() => issueId('018f0e40-5c6e-7a3f-bf6f-0c72e2d5399a')).toThrow(); expect(dependencyTarget('external:other:shipped-api')).toBe('external:other:shipped-api'); expect(issueTitle('  Plan phase one  ')).toBe('Plan phase one'); expect(issuePriority(2)).toBe(2); });
  it('accepts configured and forward-compatible vocabulary without invented built-ins', () => { expect(IssueStatusSchema.parse('queued-custom')).toBe('queued-custom'); expect(IssueTypeSchema.parse('release-candidate')).toBe('release-candidate'); expect(DependencyTypeSchema.parse('awaiting-release')).toBe('awaiting-release'); expect(IssueTypeSchema.safeParse('event').success).toBe(true); expect(DependencyTypeSchema.safeParse('waits-for').success).toBe(true); });
  it('round trips top-level and nested unknown fields through required timestamp codec', () => { const wire = issueFromBdWire(json, timestamps); expect(wire.issue).toMatchObject({ type: 'release-candidate', specId: 'spec/phase-1', branch: 'feature/hunk', metadata: { agent: 'conductor' } }); expect(wire.issue['dependencies'][0]?.wireUnknown).toEqual({ edge_future: { retained: true } }); expect(wire.issue['comments'][0]?.wireUnknown).toEqual({ comment_future: ['kept'] }); const roundTrip = issueToBdWire(wire, timestamps); expect(roundTrip['branch']).toBe('feature/hunk'); expect(roundTrip['future_field']).toEqual({ retained: true }); expect((roundTrip['dependencies'] as any)[0].edge_future).toEqual({ retained: true }); expect((roundTrip['comments'] as any)[0].comment_future).toEqual(['kept']); expect(roundTrip['created_at']).toBe(createdAt); });
  it('delegates lifecycle behavior to configured policy', () => { const at = new Date('2025-01-02T00:00:00Z'); const policy = { transition: () => ({ allowed: true as const, startedAt: at, closedAt: null }) }; expect(transitionStatus(policy, { status: 'queued-custom', startedAt: null, closedAt: null }, { from: 'queued-custom', to: 'shipped-custom', at })).toEqual({ allowed: true, startedAt: at, closedAt: null }); });
  it('rejects invalid chronology', () => { const base = { id: 'tk-5au', title: 'Plan phase one', description: '', status: 'closed', priority: 2, type: 'task', owner: null, assignee: null, createdBy: null, createdAt: new Date('2025-01-02'), updatedAt: new Date('2025-01-01'), startedAt: null, closedAt: null, dueAt: null, deferUntil: null, parentId: null, labels: [], notes: null, design: null, acceptanceCriteria: null, estimate: null, specId: null, externalRef: null, metadata: {}, dependencies: [], dependencyCount: 0, dependentCount: 0, comments: [], commentCount: 0 }; expect(IssueSchema.safeParse(base).success).toBe(false); });
  it('round trips attachments with metadata and unknown fields', () => { const withAttachments = { ...json, attachments: [{ path: 'foo.yaml', metadata: { kind: 'spec' }, attachment_future: 'kept' }, { path: 'notes/plan.md' }] }; const wire = issueFromBdWire(withAttachments, timestamps); expect(wire.issue['attachments']).toEqual([{ path: 'foo.yaml', metadata: { kind: 'spec' }, wireUnknown: { attachment_future: 'kept' } }, { path: 'notes/plan.md', metadata: {}, wireUnknown: {} }]); const roundTrip = issueToBdWire(wire, timestamps); expect(roundTrip['attachments']).toEqual([{ attachment_future: 'kept', path: 'foo.yaml', metadata: { kind: 'spec' } }, { path: 'notes/plan.md', metadata: {} }]); expect(issueFromBdWire(json, timestamps).issue['attachments']).toEqual([]); });
});

describe('agent and run domain', () => {
  const agentJson = { schema_version: 1 as const, _type: 'agent' as const, id: 'code-reviewer', name: 'Code Reviewer', description: 'Reviews diffs', owner: 'yuri', runtime: 'pi:default', access: 'workspace' as const, mode: 'autopilot' as const, status: 'online' as const, instructions: 'Be thorough', skills: ['typescript'], env: { MODEL: 'glm' }, archived_at: null, created_at: createdAt, updated_at: updatedAt, agent_future: { retained: true } };
  const runJson = { schema_version: 1 as const, _type: 'run' as const, id: 'tk-5au-run-1', issue_id: 'tk-5au', agent_id: 'code-reviewer', trigger: 'status-move' as const, state: 'running' as const, started_at: 'wire:2025-01-01T01:00:00.000Z', closed_at: null, messages: [{ at: createdAt, kind: 'log', text: 'picked up' }], usage: { tokens: 1200, cost: 0.42 }, created_at: createdAt, updated_at: updatedAt, run_future: { retained: true } };
  it('round trips agents through the domain schema and wire', () => { const wire = agentFromBdWire(agentJson, timestamps); expect(wire.agent).toMatchObject({ id: 'code-reviewer', name: 'Code Reviewer', access: 'workspace', mode: 'autopilot', status: 'online', skills: ['typescript'], env: { MODEL: 'glm' }, archivedAt: null, owner: 'yuri', runtime: 'pi:default' }); expect(wire.agent['wireUnknown']).toEqual({ agent_future: { retained: true } }); const roundTrip = agentToBdWire(wire, timestamps); expect(roundTrip['agent_future']).toEqual({ retained: true }); expect(roundTrip['archived_at']).toBeNull(); expect(roundTrip['created_at']).toBe(createdAt); expect(agentFromBdWire(roundTrip, timestamps).agent).toEqual(wire.agent); });
  it('applies agent defaults and rejects invalid fields', () => { const wire = agentFromBdWire({ id: 'scout', name: 'Scout', access: 'project', mode: 'default', status: 'idle', created_at: createdAt, updated_at: updatedAt }, timestamps); expect(wire.agent).toMatchObject({ description: '', owner: null, runtime: null, instructions: '', skills: [], env: {}, archivedAt: null }); expect(AgentSchema.safeParse({ ...wire.agent, status: 'busy' }).success).toBe(false); expect(AgentSchema.safeParse({ ...wire.agent, access: 'global' }).success).toBe(false); expect(AgentSchema.safeParse({ ...wire.agent, extra: true }).success).toBe(false); });
  it('rejects agent chronology violations', () => { const agent = AgentSchema.parse(agentFromBdWire(agentJson, timestamps).agent); expect(AgentSchema.safeParse({ ...agent, updatedAt: new Date('2024-12-31') }).success).toBe(false); expect(AgentSchema.safeParse({ ...agent, archivedAt: new Date('2024-12-31') }).success).toBe(false); });
  it('slugifies agent names like sprints', () => { expect(agentSlug('Code Reviewer!')).toBe('code-reviewer'); expect(agentSlug('3D builder')).toBe('s-3d-builder'); expect(agentSlug('  ')).toBe('agent'); });
  it('round trips runs through the domain schema and wire', () => { const wire = runFromBdWire(runJson, timestamps); expect(wire.run).toMatchObject({ id: 'tk-5au-run-1', issueId: 'tk-5au', agentId: 'code-reviewer', trigger: 'status-move', state: 'running', usage: { tokens: 1200, cost: 0.42 } }); expect(wire.run['startedAt']).toEqual(new Date('2025-01-01T01:00:00.000Z')); expect(wire.run['messages']).toEqual([{ at: new Date('2025-01-01T00:00:00.000Z'), kind: 'log', text: 'picked up' }]); expect(wire.run['wireUnknown']).toEqual({ run_future: { retained: true } }); const roundTrip = runToBdWire(wire, timestamps); expect(roundTrip['run_future']).toEqual({ retained: true }); expect(roundTrip['agent_id']).toBe('code-reviewer'); expect(roundTrip['usage']).toEqual({ tokens: 1200, cost: 0.42 }); expect(roundTrip['started_at']).toBe('wire:2025-01-01T01:00:00.000Z'); expect(runFromBdWire(roundTrip, timestamps).run).toEqual(wire.run); });
  it('applies run defaults, supports agentless runs, and rejects invalid states', () => { const wire = runFromBdWire({ id: 'tk-5au-run-2', issue_id: 'tk-5au', trigger: 'manual', state: 'queued', created_at: createdAt, updated_at: updatedAt }, timestamps); expect(wire.run).toMatchObject({ agentId: null, startedAt: null, closedAt: null, messages: [], usage: { tokens: null, cost: null } }); expect(RunSchema.safeParse({ ...wire.run, state: 'deployed' }).success).toBe(false); expect(RunSchema.safeParse({ ...wire.run, trigger: 'cron' }).success).toBe(false); expect(RunSchema.safeParse({ ...wire.run, startedAt: new Date('2024-12-31') }).success).toBe(false); expect(runId('tk-5au-run-2')).toBe('tk-5au-run-2'); expect(() => runId('018f0e40-5c6e-7a3f-bf6f-0c72e2d5399a')).toThrow(); expect(runFromBdWire({ ...runJson, agent_id: null }, timestamps).run['agentId']).toBeNull(); });
});
