import { describe, expect, it } from 'vitest';
import { IssueSchema, IssueStatusSchema, IssueTypeSchema, DependencyTypeSchema, dependencyTarget, issueFromBdWire, issueId, issuePriority, issueTitle, issueToBdWire, transitionStatus } from '../src/index.js';

const timestamps = { encode: (value: Date) => `wire:${value.toISOString()}`, decode: (value: string) => { if (!value.startsWith('wire:')) throw new Error('codec boundary used'); return new Date(value.slice(5)); } };
const createdAt = 'wire:2025-01-01T00:00:00.000Z';
const updatedAt = 'wire:2025-01-02T00:00:00.000Z';
const json = { schema_version: 1 as const, _type: 'issue' as const, id: 'tk-5au', title: 'Plan phase one', description: 'Architecture', status: 'queued-custom', priority: 2, issue_type: 'release-candidate', owner: 'owner@example.test', assignee: 'worker', created_by: 'Yuri', created_at: createdAt, updated_at: updatedAt, started_at: 'wire:2025-01-01T01:00:00.000Z', due_at: 'wire:2025-01-04T00:00:00.000Z', defer_until: null, parent: 'tk-epic', labels: ['architecture'], notes: 'note', design: 'design', acceptance_criteria: 'tests pass', estimate: 3, spec_id: 'spec/phase-1', external_ref: 'GH-42', branch: 'feature/hunk', metadata: '{"agent":"conductor"}', dependencies: [{ issue_id: 'tk-5au', depends_on_id: 'external:other:shipped-api', type: 'awaiting-release', created_at: createdAt, created_by: 'Yuri', metadata: '{}', edge_future: { retained: true } }], dependency_count: 1, comments: [{ id: 'comment-1', issue_id: 'tk-5au', author: 'Yuri', text: 'hello', created_at: createdAt, comment_future: ['kept'] }], comment_count: 1, future_field: { retained: true } };

describe('tk-compatible issue domain', () => {
  it('brands local IDs, allows explicit external targets', () => { expect(issueId('tk-5au')).toBe('tk-5au'); expect(() => issueId('018f0e40-5c6e-7a3f-bf6f-0c72e2d5399a')).toThrow(); expect(dependencyTarget('external:other:shipped-api')).toBe('external:other:shipped-api'); expect(issueTitle('  Plan phase one  ')).toBe('Plan phase one'); expect(issuePriority(2)).toBe(2); });
  it('accepts configured and forward-compatible vocabulary without invented built-ins', () => { expect(IssueStatusSchema.parse('queued-custom')).toBe('queued-custom'); expect(IssueTypeSchema.parse('release-candidate')).toBe('release-candidate'); expect(DependencyTypeSchema.parse('awaiting-release')).toBe('awaiting-release'); expect(IssueTypeSchema.safeParse('event').success).toBe(true); expect(DependencyTypeSchema.safeParse('waits-for').success).toBe(true); });
  it('round trips top-level and nested unknown fields through required timestamp codec', () => { const wire = issueFromBdWire(json, timestamps); expect(wire.issue).toMatchObject({ type: 'release-candidate', specId: 'spec/phase-1', branch: 'feature/hunk', metadata: { agent: 'conductor' } }); expect(wire.issue['dependencies'][0]?.wireUnknown).toEqual({ edge_future: { retained: true } }); expect(wire.issue['comments'][0]?.wireUnknown).toEqual({ comment_future: ['kept'] }); const roundTrip = issueToBdWire(wire, timestamps); expect(roundTrip['branch']).toBe('feature/hunk'); expect(roundTrip['future_field']).toEqual({ retained: true }); expect((roundTrip['dependencies'] as any)[0].edge_future).toEqual({ retained: true }); expect((roundTrip['comments'] as any)[0].comment_future).toEqual(['kept']); expect(roundTrip['created_at']).toBe(createdAt); });
  it('delegates lifecycle behavior to configured policy', () => { const at = new Date('2025-01-02T00:00:00Z'); const policy = { transition: () => ({ allowed: true as const, startedAt: at, closedAt: null }) }; expect(transitionStatus(policy, { status: 'queued-custom', startedAt: null, closedAt: null }, { from: 'queued-custom', to: 'shipped-custom', at })).toEqual({ allowed: true, startedAt: at, closedAt: null }); });
  it('rejects invalid chronology', () => { const base = { id: 'tk-5au', title: 'Plan phase one', description: '', status: 'closed', priority: 2, type: 'task', owner: null, assignee: null, createdBy: null, createdAt: new Date('2025-01-02'), updatedAt: new Date('2025-01-01'), startedAt: null, closedAt: null, dueAt: null, deferUntil: null, parentId: null, labels: [], notes: null, design: null, acceptanceCriteria: null, estimate: null, specId: null, externalRef: null, metadata: {}, dependencies: [], dependencyCount: 0, dependentCount: 0, comments: [], commentCount: 0 }; expect(IssueSchema.safeParse(base).success).toBe(false); });
});
