export type { Clock } from './ports/clock.js';
export type { ApplicationCompositionRoot, ApplicationPorts, MigrationFailure, MigrationHistoryEntry, MigrationPort, MigrationReport, MigrationStep } from './ports/composition-root.js';
export type { IdGenerator } from './ports/id-generator.js';
export type { AuditEntry, IssuePage, IssueQuery, IssueRepository, IssueUnitOfWork, UnitOfWork } from './ports/issue-repository.js';
export type { TimestampCodec } from './ports/timestamp-codec.js';
export { canonicalTimestampCodec } from './ports/timestamp-codec.js';
export type { TransactionManager } from './ports/transaction-manager.js';
export { err, ok } from './result.js';
export type { AppError, ConflictError, LifecycleError, MigrationError, NotFoundError, RepositoryError, Result, ValidationError } from './result.js';
export type { AddCommentUseCase, AddDependencyUseCase, ChangeIssueStatusInput, ChangeIssueStatusUseCase, ClaimReadyIssueInput, ClaimReadyIssueUseCase, CommentInput, CreateIssueInput, CreateIssueUseCase, DependencyInput, GetIssueUseCase, UpdateIssueInput, UpdateIssueUseCase } from './use-cases/issue-use-cases.js';
