import { Pool, type PoolClient, type PoolConfig, type QueryResultRow } from 'pg';
import { createHash, randomUUID } from 'node:crypto';
import { canonicalTimestampCodec, err, ok } from '@tasks/application';
import type { IssuePage, IssueQuery, IssueUnitOfWork, MigrationFailure, MigrationHistoryEntry, MigrationPort, MigrationReport, MigrationStep, Result, TimestampCodec, UnitOfWork } from '@tasks/application';
import type { Comment, DependencyEdge, Issue, IssueId, Metadata, Sprint, SprintId, Agent, AgentId, Run, RunId } from '@tasks/domain';
import { AgentSchema, IssueSchema, RunSchema, SprintSchema, agentId, agentName, runId, sprintId, sprintName } from '@tasks/domain';

export { canonicalTimestampCodec } from '@tasks/application';
export type { TimestampCodec } from '@tasks/application';
type Row = QueryResultRow & Record<string, unknown>; type Client = PoolClient; type Connection = { client: Client; release: () => void };
const INITIAL_SQL = `CREATE TABLE public.schema_migrations (id TEXT PRIMARY KEY, migration_order INTEGER NOT NULL UNIQUE, checksum TEXT NOT NULL, applied_at BIGINT NOT NULL);
CREATE TABLE public.issues (id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL,status TEXT NOT NULL,priority INTEGER NOT NULL,type TEXT NOT NULL,owner TEXT,assignee TEXT,created_by TEXT,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,started_at BIGINT,closed_at BIGINT,due_at BIGINT,defer_until BIGINT,parent_id TEXT REFERENCES public.issues(id) ON DELETE SET NULL,labels_json JSONB NOT NULL,notes TEXT,design TEXT,acceptance_criteria TEXT,estimate DOUBLE PRECISION,spec_id TEXT,external_ref TEXT,metadata_json JSONB NOT NULL,wire_unknown_json JSONB NOT NULL);
CREATE INDEX issues_parent_id_idx ON public.issues(parent_id);
CREATE TABLE public.issue_dependencies (issue_id TEXT NOT NULL REFERENCES public.issues(id) ON DELETE CASCADE,target TEXT NOT NULL,type TEXT NOT NULL,created_at BIGINT NOT NULL,created_by TEXT,metadata_json JSONB NOT NULL,wire_unknown_json JSONB NOT NULL,PRIMARY KEY(issue_id,target,type));
CREATE INDEX issue_dependencies_target_idx ON public.issue_dependencies(target);
CREATE TABLE public.issue_comments (id TEXT PRIMARY KEY,issue_id TEXT NOT NULL REFERENCES public.issues(id) ON DELETE CASCADE,author TEXT NOT NULL,text TEXT NOT NULL,created_at BIGINT NOT NULL,wire_unknown_json JSONB NOT NULL);
CREATE INDEX issue_comments_issue_idx ON public.issue_comments(issue_id,created_at);`;
const checksum = (sql: string) => createHash('sha256').update(sql).digest('hex');
const INITIAL: MigrationStep = Object.freeze({ id: '001-initial', order: 1, checksum: checksum(INITIAL_SQL), description: 'core issue persistence', sql: INITIAL_SQL });
const COMMITS_SQL = `ALTER TABLE public.issues ADD COLUMN commits_json JSONB NOT NULL DEFAULT '[]'::jsonb;`;
const COMMITS: MigrationStep = Object.freeze({ id: '002-issue-commits', order: 2, checksum: checksum(COMMITS_SQL), description: 'legacy commits field', sql: COMMITS_SQL });
const BRANCH_SQL = `ALTER TABLE public.issues ADD COLUMN branch TEXT; ALTER TABLE public.issues DROP COLUMN commits_json;`;
const BRANCH: MigrationStep = Object.freeze({ id: '003-issue-branch', order: 3, checksum: checksum(BRANCH_SQL), description: 'tracked branch per issue', sql: BRANCH_SQL });
const ATTACHMENTS_SQL = `ALTER TABLE public.issues ADD COLUMN attachments_json JSONB NOT NULL DEFAULT '[]'::jsonb;`;
const ATTACHMENTS: MigrationStep = Object.freeze({ id: '004-issue-attachments', order: 4, checksum: checksum(ATTACHMENTS_SQL), description: 'file path attachments per issue', sql: ATTACHMENTS_SQL });
const SPRINTS_SQL = `CREATE TABLE public.sprints (id TEXT PRIMARY KEY,name TEXT NOT NULL,status TEXT NOT NULL,completed_at BIGINT,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,wire_unknown_json JSONB NOT NULL);
ALTER TABLE public.issues ADD COLUMN sprint_id TEXT REFERENCES public.sprints(id);`;
const SPRINTS: MigrationStep = Object.freeze({ id: '005-sprints', order: 5, checksum: checksum(SPRINTS_SQL), description: 'focus sprints and issue membership', sql: SPRINTS_SQL });
const AGENTS_SQL = `CREATE TABLE public.agents (id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL,owner TEXT,runtime TEXT,access TEXT NOT NULL,mode TEXT NOT NULL,status TEXT NOT NULL,instructions TEXT NOT NULL,skills_json JSONB NOT NULL,env_json JSONB NOT NULL,archived_at BIGINT,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,wire_unknown_json JSONB NOT NULL);`;
const AGENTS: MigrationStep = Object.freeze({ id: '006-agents', order: 6, checksum: checksum(AGENTS_SQL), description: 'registered agents', sql: AGENTS_SQL });
const RUNS_SQL = `CREATE TABLE public.runs (id TEXT PRIMARY KEY,issue_id TEXT NOT NULL REFERENCES public.issues(id),agent_id TEXT REFERENCES public.agents(id),trigger TEXT NOT NULL,state TEXT NOT NULL,started_at BIGINT,closed_at BIGINT,messages_json JSONB NOT NULL,usage_tokens BIGINT,usage_cost DOUBLE PRECISION,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,wire_unknown_json JSONB NOT NULL);
CREATE INDEX runs_issue_id_idx ON public.runs(issue_id);`;
const RUNS: MigrationStep = Object.freeze({ id: '007-runs', order: 7, checksum: checksum(RUNS_SQL), description: 'agent runs against issues', sql: RUNS_SQL });
export const postgresMigrations: readonly MigrationStep[] = [INITIAL, COMMITS, BRANCH, ATTACHMENTS, SPRINTS, AGENTS, RUNS];
const epoch = (v: Date) => v.getTime(); const date = (v: unknown) => new Date(Number(v)); const optionalDate = (v: unknown) => v === null ? null : date(v); const json = <T>(v: unknown): T => typeof v === 'string' ? JSON.parse(v) as T : v as T; const jsonValue = (v: unknown) => JSON.stringify(v);
export interface IssuePolicy { readonly readyStatus:string; readonly claimedStatus:string; readonly terminalStatuses:readonly string[]; readonly blockerDependencyType:string; }
export const defaultIssuePolicy: IssuePolicy = Object.freeze({ readyStatus:'open', claimedStatus:'in_progress', terminalStatuses:['closed'], blockerDependencyType:'blocks' });
export interface PostgresAdapterOptions extends PoolConfig { readonly pool?: Pool; readonly client?: PoolClient; readonly timestamps?: TimestampCodec; readonly now?:()=>Date; readonly policy?:IssuePolicy; }
export class PostgresAdapter implements UnitOfWork, MigrationPort {
  readonly timestamps:TimestampCodec; readonly now:()=>Date; readonly policy:IssuePolicy; #pool:Pool|undefined; #client:PoolClient|undefined; #ownsPool:boolean;
  constructor(o:PostgresAdapterOptions={}) { this.#client=o.client; this.#pool=o.pool; this.#ownsPool=!o.client&&!o.pool; if(!this.#client&&!this.#pool) { const {pool:_p,client:_c,timestamps:_t,now:_n,policy:_policy,...config}=o; this.#pool=new Pool(config); } this.timestamps=o.timestamps??canonicalTimestampCodec;this.now=o.now??(()=>new Date());this.policy=o.policy??defaultIssuePolicy; }
  async close():Promise<void>{if(this.#ownsPool)await this.#pool?.end();}
  async #connection():Promise<Connection>{if(this.#client)return {client:this.#client,release:()=>{}};const client=await this.#pool!.connect();return {client,release:()=>client.release()};}
  async currentVersion():Promise<Result<string|null>>{try{const x=await this.#connection();try{const exists=await x.client.query(`SELECT to_regclass('public.schema_migrations') AS name`);if(!exists.rows[0]?.['name'])return ok(null);const r=await x.client.query<Row>('SELECT id FROM public.schema_migrations ORDER BY migration_order DESC LIMIT 1');return ok(r.rows[0]?String(r.rows[0]['id']):null);}finally{x.release();}}catch(cause){return err({kind:'repository',operation:'currentVersion',cause});}}
  async history():Promise<Result<readonly MigrationHistoryEntry[]>>{try{const x=await this.#connection();try{const exists=await x.client.query(`SELECT to_regclass('public.schema_migrations') AS name`);if(!exists.rows[0]?.['name'])return ok([]);const r=await x.client.query<Row>('SELECT id,migration_order,checksum,applied_at FROM public.schema_migrations ORDER BY migration_order');return ok(r.rows.map(v=>({id:String(v['id']),order:Number(v['migration_order']),checksum:String(v['checksum']),appliedAt:date(v['applied_at'])})));}finally{x.release();}}catch(cause){return err({kind:'repository',operation:'history',cause});}}
  async migrate(steps:readonly MigrationStep[]=postgresMigrations):Promise<Result<MigrationReport,MigrationFailure>>{if(!steps.length)return ok({applied:[],currentVersion:null,lockAcquired:true});let x:Connection|undefined;try{x=await this.#connection();const c=x.client;await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock($1)',[1111771443]);const bad=async(phase:MigrationFailure['phase'],message:string):Promise<Result<never,MigrationFailure>>=>{await c.query('ROLLBACK');return err({kind:'migration',phase,message});};const ids=new Set<string>();let prev=-Infinity;for(const s of steps){if(!s.id||!s.sql||s.checksum!==checksum(s.sql)||ids.has(s.id)||s.order<=prev)return await bad('validate_history',`invalid declared migration history: ${s.id}`);ids.add(s.id);prev=s.order;}const exists=await c.query(`SELECT to_regclass('public.schema_migrations') AS name`);const durable=exists.rows[0]?.['name']?(await c.query<Row>('SELECT id,migration_order,checksum FROM public.schema_migrations ORDER BY migration_order')).rows:[];for(let i=0;i<durable.length;i++){const r=durable[i]!,s=steps[i];if(!s||s.id!==String(r['id'])||s.order!==Number(r['migration_order'])||s.checksum!==String(r['checksum']))return await bad('validate_history',`durable migration history mismatch at ${String(r['id'])}`);}const applied:MigrationHistoryEntry[]=[];for(const s of steps.slice(durable.length)){await c.query(s.sql);const appliedAt=this.now();await c.query('INSERT INTO public.schema_migrations (id,migration_order,checksum,applied_at) VALUES ($1,$2,$3,$4)',[s.id,s.order,s.checksum,epoch(appliedAt)]);applied.push({id:s.id,order:s.order,checksum:s.checksum,appliedAt});}await c.query('COMMIT');return ok({applied,currentVersion:steps.at(-1)!.id,lockAcquired:true});}catch(cause){try{await x?.client.query('ROLLBACK');}catch{}return err({kind:'migration',phase:'apply',message:cause instanceof Error?cause.message:'migration failed',cause});}finally{x?.release();}}
  async hasPendingMigrations(steps:readonly MigrationStep[]=postgresMigrations):Promise<Result<boolean>>{try{const x=await this.#connection();try{const exists=await x.client.query(`SELECT to_regclass('public.schema_migrations') AS name`);if(!exists.rows[0]?.['name'])return ok(steps.length>0);const durable=(await x.client.query<Row>('SELECT id,migration_order,checksum FROM public.schema_migrations ORDER BY migration_order')).rows;if(durable.length>steps.length)return ok(true);return ok(durable.some((r,i)=>{const s=steps[i];return !s||s.id!==String(r['id'])||s.order!==Number(r['migration_order'])||s.checksum!==String(r['checksum'])})||durable.length<steps.length);}finally{x.release();}}catch(cause){return err({kind:'repository',operation:'hasPendingMigrations',cause});}}
  async withinTransaction<T>(work:(uow:IssueUnitOfWork)=>Promise<Result<T>>):Promise<Result<T>>{let x:Connection|undefined;try{x=await this.#connection();await x.client.query('BEGIN');const r=await work(new PostgresIssueUnitOfWork(this,x.client));await x.client.query(r.ok?'COMMIT':'ROLLBACK');return r;}catch(cause){try{await x?.client.query('ROLLBACK');}catch{}return err({kind:'repository',operation:'transaction',cause});}finally{x?.release();}}
  async rowToIssue(row:Row,c:Client):Promise<Issue>{const id=String(row['id']);const [dependencies,comments,dependents]=await Promise.all([c.query<Row>('SELECT * FROM public.issue_dependencies WHERE issue_id=$1',[id]),c.query<Row>('SELECT * FROM public.issue_comments WHERE issue_id=$1 ORDER BY created_at,id',[id]),c.query<Row>('SELECT count(*) AS count FROM public.issue_dependencies WHERE target=$1',[id])]);return IssueSchema.parse({id,title:row['title'],description:row['description'],status:row['status'],priority:row['priority'],type:row['type'],owner:row['owner'],assignee:row['assignee'],createdBy:row['created_by'],createdAt:date(row['created_at']),updatedAt:date(row['updated_at']),startedAt:optionalDate(row['started_at']),closedAt:optionalDate(row['closed_at']),dueAt:optionalDate(row['due_at']),deferUntil:optionalDate(row['defer_until']),parentId:row['parent_id'],sprintId:row['sprint_id'] ?? null,labels:json(row['labels_json']),notes:row['notes'],design:row['design'],acceptanceCriteria:row['acceptance_criteria'],estimate:row['estimate'],specId:row['spec_id'],externalRef:row['external_ref'],branch:row['branch'] === null || row['branch'] === undefined ? null : String(row['branch']),metadata:json(row['metadata_json']),wireUnknown:json(row['wire_unknown_json']),attachments:json(row['attachments_json'] ?? '[]'),dependencies:dependencies.rows.map(edge),dependencyCount:dependencies.rows.length,dependentCount:Number(dependents.rows[0]?.['count']),comments:comments.rows.map(comment),commentCount:comments.rows.length});}
}
const edge=(r:Row):DependencyEdge=>({issueId:String(r['issue_id']) as IssueId,target:String(r['target']) as DependencyEdge['target'],type:String(r['type']),createdAt:date(r['created_at']),createdBy:r['created_by']===null?null:String(r['created_by']),metadata:json<Metadata>(r['metadata_json']),wireUnknown:json<Metadata>(r['wire_unknown_json'])}); const comment=(r:Row):Comment=>({id:String(r['id']),issueId:String(r['issue_id']) as IssueId,author:String(r['author']),text:String(r['text']),createdAt:date(r['created_at']),wireUnknown:json<Metadata>(r['wire_unknown_json'])});
class PostgresIssueUnitOfWork implements IssueUnitOfWork {
 constructor(private readonly a:PostgresAdapter,private readonly c:Client){}
 async history(id:IssueId):Promise<Result<readonly import('@tasks/application').AuditEntry[]>>{return ok([]);}
 async findById(id:IssueId):Promise<Result<Issue|null>>{try{const r=await this.c.query<Row>('SELECT * FROM public.issues WHERE id=$1',[id]);return ok(r.rows[0]?await this.a.rowToIssue(r.rows[0],this.c):null);}catch(cause){return err({kind:'repository',operation:'findById',cause});}}
 async list(q:IssueQuery):Promise<Result<IssuePage>>{try{const clauses:string[]=[],values:unknown[]=[];if(q.status){values.push(q.status);clauses.push(`status=$${values.length}`);}if(q.cursor){values.push(q.cursor);clauses.push(`id>$${values.length}`);}const limit=q.limit??100;values.push(limit+1);const rows=(await this.c.query<Row>(`SELECT * FROM public.issues ${clauses.length?`WHERE ${clauses.join(' AND ')}`:''} ORDER BY id LIMIT $${values.length}`,values)).rows;const items=await Promise.all(rows.slice(0,limit).map(r=>this.a.rowToIssue(r,this.c)));return ok({items,nextCursor:rows.length>limit?items.at(-1)!.id:null});}catch(cause){return err({kind:'repository',operation:'list',cause});}}
 async save(i:Issue):Promise<Result<void>>{try{const issue=IssueSchema.parse(i);const dt=(v:Date|null)=>v===null?null:epoch(v);await this.c.query(`INSERT INTO public.issues (id,title,description,status,priority,type,owner,assignee,created_by,created_at,updated_at,started_at,closed_at,due_at,defer_until,parent_id,sprint_id,labels_json,notes,design,acceptance_criteria,estimate,spec_id,external_ref,branch,metadata_json,attachments_json,wire_unknown_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18::jsonb,$19,$20,$21,$22,$23,$24,$25,$26::jsonb,$27::jsonb,$28::jsonb) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,status=EXCLUDED.status,priority=EXCLUDED.priority,type=EXCLUDED.type,owner=EXCLUDED.owner,assignee=EXCLUDED.assignee,created_by=EXCLUDED.created_by,created_at=EXCLUDED.created_at,updated_at=EXCLUDED.updated_at,started_at=EXCLUDED.started_at,closed_at=EXCLUDED.closed_at,due_at=EXCLUDED.due_at,defer_until=EXCLUDED.defer_until,parent_id=EXCLUDED.parent_id,sprint_id=EXCLUDED.sprint_id,labels_json=EXCLUDED.labels_json,notes=EXCLUDED.notes,design=EXCLUDED.design,acceptance_criteria=EXCLUDED.acceptance_criteria,estimate=EXCLUDED.estimate,spec_id=EXCLUDED.spec_id,external_ref=EXCLUDED.external_ref,branch=EXCLUDED.branch,metadata_json=EXCLUDED.metadata_json,attachments_json=EXCLUDED.attachments_json,wire_unknown_json=EXCLUDED.wire_unknown_json`,[i.id,i.title,i.description,i.status,i.priority,i.type,i.owner,i.assignee,i.createdBy,epoch(i.createdAt),epoch(i.updatedAt),dt(i.startedAt),dt(i.closedAt),dt(i.dueAt),dt(i.deferUntil),i.parentId,i.sprintId,jsonValue(issue.labels),i.notes,i.design,i.acceptanceCriteria,i.estimate,i.specId,i.externalRef,issue.branch,jsonValue(issue.metadata),jsonValue(issue.attachments),jsonValue(issue.wireUnknown)]);await this.c.query('DELETE FROM public.issue_dependencies WHERE issue_id=$1',[i.id]);await this.c.query('DELETE FROM public.issue_comments WHERE issue_id=$1',[i.id]);for(const e of i.dependencies)await this.addDependency(e);for(const x of i.comments)await this.c.query('INSERT INTO public.issue_comments (id,issue_id,author,text,created_at,wire_unknown_json) VALUES ($1,$2,$3,$4,$5,$6::jsonb)',[x.id,x.issueId,x.author,x.text,epoch(x.createdAt),jsonValue(x.wireUnknown)]);return ok(undefined);}catch(cause){return err({kind:'repository',operation:'save',cause});}}
 async addDependency(e:DependencyEdge):Promise<Result<void>>{try{await this.c.query('INSERT INTO public.issue_dependencies (issue_id,target,type,created_at,created_by,metadata_json,wire_unknown_json) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb) ON CONFLICT (issue_id,target,type) DO UPDATE SET created_at=EXCLUDED.created_at,created_by=EXCLUDED.created_by,metadata_json=EXCLUDED.metadata_json,wire_unknown_json=EXCLUDED.wire_unknown_json',[e.issueId,e.target,e.type,epoch(e.createdAt),e.createdBy,jsonValue(e.metadata),jsonValue(e.wireUnknown)]);return ok(undefined);}catch(cause){return err({kind:'repository',operation:'addDependency',cause});}}
 async removeDependency(id:IssueId,target:DependencyEdge['target'],type?:DependencyEdge['type']):Promise<Result<void>>{try{await this.c.query(type?'DELETE FROM public.issue_dependencies WHERE issue_id=$1 AND target=$2 AND type=$3':'DELETE FROM public.issue_dependencies WHERE issue_id=$1 AND target=$2',type?[id,target,type]:[id,target]);return ok(undefined);}catch(cause){return err({kind:'repository',operation:'removeDependency',cause});}}
 async addComment(id:IssueId,author:string,text:string):Promise<Result<void>>{try{await this.c.query('INSERT INTO public.issue_comments (id,issue_id,author,text,created_at,wire_unknown_json) VALUES ($1,$2,$3,$4,$5,$6::jsonb)',[`comment-${randomUUID()}`,id,author,text,epoch(this.a.now()),'{}']);return ok(undefined);}catch(cause){return err({kind:'repository',operation:'addComment',cause});}}
 async delete(id:IssueId):Promise<Result<void>>{try{await this.c.query('DELETE FROM public.issue_dependencies WHERE issue_id=$1 OR target=$1',[id]);await this.c.query('DELETE FROM public.issue_comments WHERE issue_id=$1',[id]);await this.c.query('DELETE FROM public.issue_history WHERE issue_id=$1',[id]);await this.c.query('UPDATE public.issues SET parent_id=NULL WHERE parent_id=$1',[id]);await this.c.query('DELETE FROM public.issues WHERE id=$1',[id]);return ok(undefined);}catch(cause){return err({kind:'repository',operation:'delete',cause});}}
 async claimReady(id:IssueId,assignee:string,expectedUpdatedAt?:Date):Promise<Result<Issue>>{try{const now=epoch(this.a.now()),p=this.a.policy,values:unknown[]=[assignee,p.claimedStatus,now,now,id,p.readyStatus,now];let expected='';if(expectedUpdatedAt){values.push(epoch(expectedUpdatedAt));expected=` AND i.updated_at=$${values.length}`;}values.push(p.blockerDependencyType);const blocker=values.length;const terminals=p.terminalStatuses.map(s=>{values.push(s);return `$${values.length}`;});const r=await this.c.query<Row>(`UPDATE public.issues AS i SET assignee=$1,status=$2,started_at=COALESCE(i.started_at,$3),updated_at=$4 WHERE i.id=$5 AND i.status=$6 AND (i.defer_until IS NULL OR i.defer_until<=$7)${expected} AND NOT EXISTS (SELECT 1 FROM public.issue_dependencies d JOIN public.issues blocker ON blocker.id=d.target WHERE d.issue_id=i.id AND d.type=$${blocker} AND blocker.status NOT IN (${terminals.join(',')})) RETURNING i.*`,values);if(r.rowCount!==1||!r.rows[0])return err({kind:'conflict',message:'issue not ready or claim lost race'});return ok(await this.a.rowToIssue(r.rows[0],this.c));}catch(cause){return err({kind:'repository',operation:'claimReady',cause});}}
 #sprint(r:Row):Sprint{return SprintSchema.parse({id:sprintId(String(r['id'])),name:sprintName(String(r['name'])),status:String(r['status'])==='completed'?'completed':'active',completedAt:optionalDate(r['completed_at']),createdAt:date(r['created_at']),updatedAt:date(r['updated_at']),wireUnknown:json<Metadata>(r['wire_unknown_json'] ?? '{}')});}
 async listSprints():Promise<Result<readonly Sprint[]>>{try{const r=await this.c.query<Row>('SELECT * FROM public.sprints ORDER BY created_at,id');return ok(r.rows.map(row=>this.#sprint(row)));}catch(cause){return err({kind:'repository',operation:'listSprints',cause});}}
 async findSprint(id:SprintId):Promise<Result<Sprint|null>>{try{const r=await this.c.query<Row>('SELECT * FROM public.sprints WHERE id=$1',[id]);return ok(r.rows[0]?this.#sprint(r.rows[0]):null);}catch(cause){return err({kind:'repository',operation:'findSprint',cause});}}
 async saveSprint(sprint:Sprint):Promise<Result<void>>{try{const parsed=SprintSchema.parse(sprint);await this.c.query(`INSERT INTO public.sprints (id,name,status,completed_at,created_at,updated_at,wire_unknown_json) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,status=EXCLUDED.status,completed_at=EXCLUDED.completed_at,created_at=EXCLUDED.created_at,updated_at=EXCLUDED.updated_at,wire_unknown_json=EXCLUDED.wire_unknown_json`,[parsed.id,parsed.name,parsed.status,parsed.completedAt===null?null:epoch(parsed.completedAt),epoch(parsed.createdAt),epoch(parsed.updatedAt),jsonValue(parsed.wireUnknown)]);return ok(undefined);}catch(cause){return err({kind:'repository',operation:'saveSprint',cause});}}
 #agent(r:Row):Agent{return AgentSchema.parse({id:agentId(String(r['id'])),name:agentName(String(r['name'])),description:String(r['description']),owner:r['owner']===null?null:String(r['owner']),runtime:r['runtime']===null?null:String(r['runtime']),access:String(r['access']),mode:String(r['mode']),status:String(r['status']),instructions:String(r['instructions']),skills:json<string[]>(r['skills_json'] ?? '[]'),env:json<Record<string,string>>(r['env_json'] ?? '{}'),archivedAt:optionalDate(r['archived_at']),createdAt:date(r['created_at']),updatedAt:date(r['updated_at']),wireUnknown:json<Metadata>(r['wire_unknown_json'] ?? '{}')});}
 async listAgents():Promise<Result<readonly Agent[]>>{try{const r=await this.c.query<Row>('SELECT * FROM public.agents ORDER BY created_at,id');return ok(r.rows.map(row=>this.#agent(row)));}catch(cause){return err({kind:'repository',operation:'listAgents',cause});}}
 async findAgent(id:AgentId):Promise<Result<Agent|null>>{try{const r=await this.c.query<Row>('SELECT * FROM public.agents WHERE id=$1',[id]);return ok(r.rows[0]?this.#agent(r.rows[0]):null);}catch(cause){return err({kind:'repository',operation:'findAgent',cause});}}
 async saveAgent(agent:Agent):Promise<Result<void>>{try{const parsed=AgentSchema.parse(agent);await this.c.query(`INSERT INTO public.agents (id,name,description,owner,runtime,access,mode,status,instructions,skills_json,env_json,archived_at,created_at,updated_at,wire_unknown_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12,$13,$14,$15::jsonb) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,owner=EXCLUDED.owner,runtime=EXCLUDED.runtime,access=EXCLUDED.access,mode=EXCLUDED.mode,status=EXCLUDED.status,instructions=EXCLUDED.instructions,skills_json=EXCLUDED.skills_json,env_json=EXCLUDED.env_json,archived_at=EXCLUDED.archived_at,created_at=EXCLUDED.created_at,updated_at=EXCLUDED.updated_at,wire_unknown_json=EXCLUDED.wire_unknown_json`,[parsed.id,parsed.name,parsed.description,parsed.owner,parsed.runtime,parsed.access,parsed.mode,parsed.status,parsed.instructions,jsonValue(parsed.skills),jsonValue(parsed.env),parsed.archivedAt===null?null:epoch(parsed.archivedAt),epoch(parsed.createdAt),epoch(parsed.updatedAt),jsonValue(parsed.wireUnknown)]);return ok(undefined);}catch(cause){return err({kind:'repository',operation:'saveAgent',cause});}}
 #run(r:Row):Run{return RunSchema.parse({id:runId(String(r['id'])),issueId:String(r['issue_id']),agentId:r['agent_id']===null?null:agentId(String(r['agent_id'])),trigger:String(r['trigger']),state:String(r['state']),startedAt:optionalDate(r['started_at']),closedAt:optionalDate(r['closed_at']),messages:(json<{at:number;kind:string;text:string}[]>(r['messages_json'] ?? '[]')).map(m=>({at:date(m.at),kind:m.kind,text:m.text})),usage:{tokens:r['usage_tokens']===null?null:Number(r['usage_tokens']),cost:r['usage_cost']===null?null:Number(r['usage_cost'])},createdAt:date(r['created_at']),updatedAt:date(r['updated_at']),wireUnknown:json<Metadata>(r['wire_unknown_json'] ?? '{}')});}
 async listRuns(issueId?:IssueId):Promise<Result<readonly Run[]>>{try{const r=await this.c.query<Row>('SELECT * FROM public.runs WHERE $1::text IS NULL OR issue_id=$1 ORDER BY created_at,id',[issueId ?? null]);return ok(r.rows.map(row=>this.#run(row)));}catch(cause){return err({kind:'repository',operation:'listRuns',cause});}}
 async findRun(id:RunId):Promise<Result<Run|null>>{try{const r=await this.c.query<Row>('SELECT * FROM public.runs WHERE id=$1',[id]);return ok(r.rows[0]?this.#run(r.rows[0]):null);}catch(cause){return err({kind:'repository',operation:'findRun',cause});}}
 async saveRun(run:Run):Promise<Result<void>>{try{const parsed=RunSchema.parse(run);await this.c.query(`INSERT INTO public.runs (id,issue_id,agent_id,trigger,state,started_at,closed_at,messages_json,usage_tokens,usage_cost,created_at,updated_at,wire_unknown_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,$12,$13::jsonb) ON CONFLICT (id) DO UPDATE SET issue_id=EXCLUDED.issue_id,agent_id=EXCLUDED.agent_id,trigger=EXCLUDED.trigger,state=EXCLUDED.state,started_at=EXCLUDED.started_at,closed_at=EXCLUDED.closed_at,messages_json=EXCLUDED.messages_json,usage_tokens=EXCLUDED.usage_tokens,usage_cost=EXCLUDED.usage_cost,created_at=EXCLUDED.created_at,updated_at=EXCLUDED.updated_at,wire_unknown_json=EXCLUDED.wire_unknown_json`,[parsed.id,parsed.issueId,parsed.agentId,parsed.trigger,parsed.state,parsed.startedAt===null?null:epoch(parsed.startedAt),parsed.closedAt===null?null:epoch(parsed.closedAt),jsonValue(parsed.messages.map(m=>({at:epoch(m.at),kind:m.kind,text:m.text}))),parsed.usage.tokens,parsed.usage.cost,epoch(parsed.createdAt),epoch(parsed.updatedAt),jsonValue(parsed.wireUnknown)]);return ok(undefined);}catch(cause){return err({kind:'repository',operation:'saveRun',cause});}}
}
